# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

########################
#  MAIN CONFIGURATION  #
########################

c.session.default_name = "default"

# search engines
c.url.searchengines = {
    "DEFAULT": "https://duckduckgo.com/?q={}",
    "aur"    : "https://aur.archlinux.org/packages/?K={}",
    "gt"     : "https://translate.google.com/#fr/en/{}",
    "w"      : "https://fr.wikipedia.org/wiki/{}",
    "wen"    : "https://en.wikipedia.org/wiki/{}",
    "aw"     : "https://wiki.archlinux.org/?search={}",
    "cppref" : "http://en.cppreference.com/mwiki/?search={}",
    "yt"     : "https://www.youtube.com/results?search_query={}",
    "gh"     : "https://github.com/search?q={}"
}

c.spellcheck.languages = ["fr-FR", "en-CA"]

##################
#  KEY BINDINGS  #
##################

# general
## passthrough allow ctrl-v for pasting clipboard
config.unbind('<ctrl-v>', mode='passthrough')
config.bind('<ctrl-z>','leave-mode', mode='passthrough')

#netflix
c.qt.args = ['ppapi-widevine-path=/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so']
