# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

########################
#  MAIN CONFIGURATION  #
########################

c.session.default_name = "default"

# search engines
c.url.searchengines = {
    "DEFAULT": "https://duckduckgo.com/?q={}",
    "aur"    : "https://aur.archlinux.org/packages/?K={}",
    "gt"     : "https://translate.google.com/#fr/en/{}",
    "w"      : "https://fr.wikipedia.org/wiki/{}",
    "wen"    : "https://en.wikipedia.org/wiki/{}",
    "aw"     : "https://wiki.archlinux.org/?search={}",
    "cppref" : "http://en.cppreference.com/mwiki/?search={}",
    "yt"     : "https://www.youtube.com/results?search_query={}",
    "gh"     : "https://github.com/search?q={}"
}

c.spellcheck.languages = ["fr-FR", "en-CA"]

#################
#     FONTS     #
################

font_size = "9pt"
c.fonts.completion.category = "bold "+font_size+" monospace"
c.fonts.completion.entry = font_size+" monospace"
c.fonts.debug_console = font_size+" monospace"
c.fonts.downloads = font_size+" monospace"
c.fonts.hints = "bold "+font_size+" monospace"
c.fonts.keyhint = font_size+" monospace"
c.fonts.messages.error = font_size+" monospace"
c.fonts.messages.info = font_size+" monospace"
c.fonts.messages.warning = font_size+" monospace"
c.fonts.prompts = font_size+" sans-serif"
c.fonts.statusbar = font_size+" monospace"
c.fonts.tabs = font_size+" monospace"

##################
#  KEY BINDINGS  #
##################

# general
## passthrough allow ctrl-v for pasting clipboard
config.unbind('<ctrl-v>', mode='passthrough')
config.bind('<ctrl-z>','leave-mode', mode='passthrough')

#netflix
c.qt.args = ['ppapi-widevine-path=/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so']
